"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowRight, Check, Sparkles } from "lucide-react";
import { tools } from "@/src/data/tools";
import { addProject } from "@/src/lib/uiState";

const steps=["Project details","Requirements","Recommended tools","Roadmap preview","Start building"];
export function ProjectBuilder(){
 const router=useRouter(); const [step,setStep]=useState(1); const [name,setName]=useState(""); const [description,setDescription]=useState(""); const [about,setAbout]=useState(""); const [idea,setIdea]=useState(""); const [saved,setSaved]=useState(false); const [selected,setSelected]=useState<string[]>([]);
 const next=()=>setStep(s=>Math.min(5,s+1));
 const save=()=>{const p=addProject({name:name||"Untitled Forge",description,idea:`${about}\n${idea}`,progress:0,phase:"Planning"});setSaved(true); localStorage.setItem("forge-it-current-project",p.id)};
 return <div className="project-builder"><div className="step-rail">{steps.map((s,i)=><button type="button" key={s} className={step===i+1?"step active":"step"} onClick={()=>setStep(i+1)}><span>{i+1}</span><b>{s}</b></button>)}</div><div className="builder-main">
 {step===1&&<><h2>Tell Forge-IT what you want to build.</h2><p className="muted">This information is used by the recommendation and roadmap engines.</p><label>What’s the name of the project?<input value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. AI Study Assistant" /></label><label>What is the project going to do?<textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="Describe the outcome in plain language." /></label><label>What is the project about?<textarea value={about} onChange={e=>setAbout(e.target.value)} placeholder="What problem does it solve and who is it for?" /></label><label>What’s the basic idea outline?<textarea value={idea} onChange={e=>setIdea(e.target.value)} placeholder="Example: input → process → output → launch" /></label><button className="primary-button" onClick={()=>setStep(2)}>Continue <ArrowRight size={16}/></button></>}
 {step===2&&<><h2>Shape the first version.</h2><div className="prompt-card"><b>Core requirement</b><p>Define the smallest useful version first. Forge-IT will use this to avoid an overbuilt roadmap.</p></div><label>Must-have features<textarea placeholder="Authentication, dashboard, AI assistant..." /></label><button className="primary-button" onClick={()=>setStep(3)}>Analyze & suggest tools <Sparkles size={16}/></button></>}
 {step===3&&<><h2>Recommended tools for this project.</h2><p className="muted">Select the tools you want Forge-IT to carry into your roadmap.</p><div className="tool-grid compact">{tools.map(t=><button type="button" className="tool-card" key={t.name} onClick={()=>setSelected(v=>v.includes(t.name)?v.filter(x=>x!==t.name):[...v,t.name])} aria-pressed={selected.includes(t.name)}><div className="tool-logo">{t.name[0]}</div><div><h3>{t.name}</h3><p>{t.description}</p><span className="tag">{t.match}% match</span></div><div>{selected.includes(t.name)?<Check color="#2e9b60"/>:<span className="tag">Select</span>}</div></button>)}</div><button className="primary-button" onClick={()=>setStep(4)}>Build roadmap <ArrowRight size={16}/></button></>}
 {step===4&&<><h2>Your roadmap is ready to review.</h2><div className="roadmap-preview">{["Planning","Setup","Design","Development","Testing","Deployment"].map((x,i)=><div key={x}><span>{i+1}</span><div><b>{x}</b><small>{i<2?"Ready":"Estimated"}</small></div></div>)}</div><button className="primary-button" onClick={()=>{save();next()}}>Create project <ArrowRight size={16}/></button></>}
 {step===5&&<><h2>{saved?"Project created.":"Let’s build it."}</h2><p>Your project is now persisted locally for this demo. Continue into your workspace and pick up the first task.</p><div className="builder-success"><b>Next task</b><span>Set up the project foundation</span></div><div className="hero-actions"><button className="primary-button" onClick={()=>router.push('/dashboard')}>Open dashboard <ArrowRight size={16}/></button><button className="secondary-button" onClick={()=>router.push('/roadmap')}>View roadmap</button></div></>}
 </div></div>
}
