server.port=8080
spring.application.name=forge-it
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:forgeit
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# Swagger/OpenAPI Configuration
springdoc.api-docs.path=/api/v3/api-docs
springdoc.swagger-ui.path=/api/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.operations-sorter=method

# Logging
logging.level.root=WARN
logging.level.com.forgeit=INFO

# JSON formatting
spring.jackson.serialization.indent-output=true
